# Configuration: https://rust-lang.github.io/rustfmt/
brace_style = "AlwaysNextLine"
chain_width = 75
comment_width = 80
edition = "2024"
force_multiline_blocks = true
format_strings = true
group_imports = "StdExternalCrate"
hard_tabs = true
imports_granularity = "Module"
imports_layout = "HorizontalVertical"
match_arm_leading_pipes = "Always"
max_width = 80
merge_derives = false
single_line_let_else_max_width = 75
reorder_impl_items = true
tab_spaces = 4
unstable_features = true
use_field_init_shorthand = true
wrap_comments = true
