[workspace]
members = ["libs/cargo/*", "www/flex-ws-server"]
resolver = "2"

[workspace.package]
# name = "flex"
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
chrono = { version = "0.4.34", features = ["clock", "serde"] }
dashmap = { version = "5.5.3", features = ["serde"] }
lexa-kernel = { git = "https://github.com/PhiSyX/lexa-kernel.git", rev = "76efd03faec3de953761b6cd5c07ec78c9d73947", features = [
	"tracing",
] }
log = { version = "0.4.20" }
flex-cli = { path = "libs/cargo/flex-cli" }
flex-crypto = { path = "libs/cargo/flex-crypto" }
flex-serde-validation = { path = "libs/cargo/flex-serde-validation" }
flex-web-framework = { path = "libs/cargo/flex-web-framework" }
serde = { version = "1.0.196", features = ["derive"] }
socketioxide = { version = "0.10.2", features = ["extensions", "state"] }
thiserror = { version = "1.0.57" }
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread"] }
tracing = { version = "0.1.40" }
uuid = { version = "1.7.0", features = ["v4", "serde"] }
