[workspace]
members = ["libs/cargo/*", "www/flex"]
resolver = "2"

[workspace.package]
# name = "flex"
version = "0.1.0"
edition = "2021"

[workspace.lints.rust]
non_camel_case_types = "allow"
async_fn_in_trait = "allow"
# unsafe_code = "forbid"

[workspace.dependencies]
chrono = { version = "0.4.37", features = ["clock", "serde"] }
dashmap = { version = "5.5.3", features = ["serde"] }
lexa-kernel = { git = "https://github.com/PhiSyX/lexa-kernel.git", rev = "76a319c600921e3cef7085d0fd3300a4dee78948", features = [
	"tracing",
] }
log = { version = "0.4.21" }
flex-cli = { path = "libs/cargo/flex-cli" }
flex-crypto = { path = "libs/cargo/flex-crypto" }
flex-serde-validation = { path = "libs/cargo/flex-serde-validation" }
flex-web-framework = { path = "libs/cargo/flex-web-framework" }
serde = { version = "1.0.197", features = ["derive"] }
sqlx = { version = "0.7.4", features = ["chrono", "postgres", "uuid"] }
socketioxide = { version = "0.12.0", features = ["extensions", "state"] }
thiserror = { version = "1.0.58" }
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread"] }
tracing = { version = "0.1.40" }
uuid = { version = "1.8.0", features = ["v4", "serde"] }
