[workspace]
members = ["libs/cargo/*", "www/flex-ws-server"]
resolver = "2"

[workspace.package]
# name = "flex"
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
lexa-kernel = { git = "https://github.com/PhiSyX/lexa-kernel.git", rev = "502d13e78c1bf068c521d33abedae1c2271c9116" }
log = { version = "0.4.20" }
flex-cli = { path = "libs/cargo/flex-cli" }
flex-crypto = { path = "libs/cargo/flex-crypto" }
flex-serde-validation = { path = "libs/cargo/flex-serde-validation" }
flex-web-framework = { path = "libs/cargo/flex-web-framework" }
serde = { version = "1.0.195", features = ["derive"] }
thiserror = { version = "1.0.56" }
tokio = { version = "1.35.1", features = ["macros", "rt-multi-thread"] }
