packages:
  - apps/**
  - assets
  - libs/npm/**
  - libs/scss/**
  - tools/**
  - www/**

catalog:
  "sass-embedded": ^1.90.0
  typescript: ^5.8.3
  vite: ^7.0.6
  vitest: ^3.1.1
  vue: ^3.5.13
  vue-tsc: ^3.0.5

onlyBuiltDependencies:
  - "@biomejs/biome"
  - argon2
  - esbuild

ignoredBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - vue-demi
