packages:
  - "apps/**"
  - "assets"
  - "libs/npm/**"
  - "libs/scss/**"
  - "tools/**"
  - "www/**"

catalog:
  sass: ^1.83.0
  typescript: ^5.7.2
  vite: ^6.0.7
  vitest: ^2.1.6
  vue: ^3.5.13
  vue-tsc: ^2.2.0
