packages:
  - "apps/**"
  - "assets"
  - "libs/npm/**"
  - "libs/scss/**"
  - "tools/**"
  - "www/**"

catalog:
  sass: ^1.80.4
  typescript: ^5.6.3
  vite: ^5.4.10
  vitest: ^2.1.3
  vue: ^3.5.12
  vue-tsc: ^2.1.6
