packages:
  - apps/**
  - assets
  - libs/npm/**
  - libs/scss/**
  - tools/**
  - www/**
catalog:
  sass: ^1.86.3
  typescript: ^5.8.3
  vite: ^6.2.5
  vitest: ^3.1.1
  vue: ^3.5.13
  vue-tsc: ^2.2.8

onlyBuiltDependencies:
  - '@biomejs/biome'
  - argon2
  - esbuild
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - vue-demi
