# https://taskfile.dev

version: "3"

tasks:
  code-quality:
    cmds:
      - echo "Cargo checks code quality..."
      - cargo clippy --workspace --all-features -- -D warnings -A dead_code --no-deps
      - cargo fmt --check
      - echo "NPM checks code quality..."
      - pnpm lint
    silent: true

  tests:
    deps:
      - cargo:test:unit
      - npm:test:unit

  tests-ci:
    deps:
      - cargo:test:unit
      - npm:test:unit
      - npm:test:e2e-ci


######################
#        Test        #
######################

  cargo:test:unit:
    cmds:
      - cargo test

  npm:test:unit:
    cmds:
      - pnpm -w run test:unit

  npm:test:e2e-ci:
    vars: { CI: true }
    cmds:
      - CI={{.CI}} pnpm -w run test:e2e
