# Les champs en commentaires ne sont pas obligatoires.

cors:
  preset: default
  allow_credentials: true
  allow_origin:
    - "http://localhost:5173" # à changer, au cas où (HTTPS?)
  allow_headers:
    - "Content-Type"

#cookie:
#  domain: ""
#  path: "/"
#  max_age: 7200
#  http_only: true
#  secure: true
#  same_site: Lax

network:
  name: Nom d'example

admin:
  name: "John Doe"
  email: johndoe@example.com
  nick: JohnDoe

server:
  name: chat.example.com

  #
  # Mot de passe
  #
  # 1. Dé-commenter le champ `password`.
  # 2. Lancer dans le terminal: `./flex make-generate <password>`
  # 3. Copier le mot de passe généré et le coller dans le champ `password`.
  #
  #password: "$argon2id..."

  #
  # Date de création du serveur.
  #
  #created_at: 1635185135

operator:
  auto_join: ["#headquarter", "#staff"]

operators:
  - identifier: JohnDoe
    password: "$argon2id..."
    type: GlobalOperator #| LocalOperator
    #vhost: example.org/johndoe
    #flags: [NoKick]
